# Generated by Django 4.2.11 on 2024-05-11 15:34

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to='images/'),
        ),
    ]
