# Generated by Django 4.2.11 on 2024-05-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_alter_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="wasTraded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="item/images/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
