# Generated by Django 5.0.4 on 2024-05-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0005_alter_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="item/images/"),
        ),
    ]
