# Generated by Django 5.0.3 on 2024-05-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0008_rename_wastraded_item_was_traded_alter_item_image"),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO item_category(name) 
            VALUES 
            ('Herramientas manuales'),
            ('Herramientas eléctricas'),
            ('Equipo de seguridad'),
            ('Ferretería para hogar'),
            ('Suministros de construcción'),
            ('Equipamiento de jardín'),
            ('Accesorios de fontanería');
        """)
    ]