# Generated by Django 5.0.3 on 2024-06-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0009_auto_20240515_2249"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
