# Generated by Django 5.0.3 on 2024-05-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_alter_employee_branch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch_id',
        ),
    ]
