# Generated by Django 5.0.6 on 2024-05-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_branch_employees_alter_branch_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='employees',
        ),
    ]
