# Generated by Django 5.0.4 on 2024-06-26 13:18

import core.jobs
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owners", "0004_remove_branch_employees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="titulo")),
                (
                    "image",
                    models.ImageField(
                        upload_to=core.jobs.UploadToPathAndRename("product/images/")
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
            },
        ),
    ]
