# Generated by Django 5.0.6 on 2024-07-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.CharField(default=0, max_length=10, verbose_name='sold'),
            preserve_default=False,
        ),
    ]
