# Generated by Django 5.0.6 on 2024-07-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0006_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
