# Generated by Django 5.0.3 on 2024-05-15 09:30

import core.jobs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="avatars/avatar-default.jpg",
                upload_to=core.jobs.UploadToPathAndRename("avatars"),
            ),
        ),
    ]
