# Generated by Django 5.0.3 on 2024-07-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="valoration",
            field=models.FloatField(default=0.0),
        ),
    ]
