# Generated by Django 5.0.3 on 2024-07-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_valoration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="valoration",
            field=models.IntegerField(default=0),
        ),
    ]
