# Generated by Django 5.0.3 on 2024-05-29 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("item", "0009_auto_20240515_2249"),
        ("owners", "0004_remove_branch_employees"),
        ("user", "0004_alter_user_first_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Estado")),
            ],
        ),
        migrations.CreateModel(
            name="DateTuple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="AcceptedTrade",
            fields=[
                (
                    "state_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trades.state",
                    ),
                ),
            ],
            bases=("trades.state",),
        ),
        migrations.CreateModel(
            name="CanceledTrade",
            fields=[
                (
                    "state_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trades.state",
                    ),
                ),
            ],
            bases=("trades.state",),
        ),
        migrations.CreateModel(
            name="PendingTrade",
            fields=[
                (
                    "state_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trades.state",
                    ),
                ),
            ],
            bases=("trades.state",),
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("replied_at", models.DateField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="owners.branch",
                        verbose_name="Sucursal elegida",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.employee"
                    ),
                ),
                (
                    "offered_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offered_item",
                        to="item.item",
                        verbose_name="Articulo ofrecido",
                    ),
                ),
                (
                    "offering_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requesting_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario solicitante",
                    ),
                ),
                (
                    "requested_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_item",
                        to="item.item",
                        verbose_name="Articulo solicitado",
                    ),
                ),
                (
                    "requested_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario solicitado",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trades.state",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeDateTuple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_tuple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trades.datetuple",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trades.trade"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trade",
            name="selected_dates",
            field=models.ManyToManyField(
                through="trades.TradeDateTuple",
                to="trades.datetuple",
                verbose_name="Fechas seleccionadas",
            ),
        ),
    ]
