# Generated by Django 5.0.3 on 2024-06-01 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("item", "0009_auto_20240515_2249"),
        ("owners", "0004_remove_branch_employees"),
        ("user", "0004_alter_user_first_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DateSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Acepted"),
                            ("DECLINED", "Declined"),
                            ("COUNTEROFFERED", "Counteroffered"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="owners.branch",
                        verbose_name="Sucursal elegida",
                    ),
                ),
                (
                    "offered_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offered_item",
                        to="item.item",
                        verbose_name="Articulo ofrecido",
                    ),
                ),
                (
                    "offering_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requesting_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario solicitante",
                    ),
                ),
                (
                    "possible_dates",
                    models.ManyToManyField(
                        to="trades.dateselection",
                        verbose_name="Fechas posibles para el encuentro",
                    ),
                ),
                (
                    "previous_proposal",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trades.proposal",
                        verbose_name="Propuesta previa",
                    ),
                ),
                (
                    "requested_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_item",
                        to="item.item",
                        verbose_name="Articulo solicitado",
                    ),
                ),
                (
                    "requested_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario solicitado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Acepted"),
                            ("CANCELED", "Canceled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("agreed_date", models.DateTimeField(verbose_name="Fecha acordada")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="owners.branch"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="user.employee",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trades.proposal",
                        verbose_name="Propuesta",
                    ),
                ),
            ],
        ),
    ]
