# Generated by Django 5.0.3 on 2024-06-01 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="previous_proposal",
            new_name="counteroffer_to",
        ),
        migrations.RenameField(
            model_name="proposal",
            old_name="branch",
            new_name="possible_branch",
        ),
        migrations.AddField(
            model_name="proposal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proposal",
            name="replied_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="confirmed_at",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
