# Generated by Django 5.0.3 on 2024-06-04 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0003_proposal_confirmed_date_alter_proposal_state"),
        ("user", "0004_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.employee",
            ),
        ),
    ]
