# Generated by Django 5.0.3 on 2024-06-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0004_alter_trade_confirmed_at_alter_trade_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
