# Generated by Django 5.0.6 on 2024-06-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_proposal_updated_at_trade_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
