# Generated by Django 5.0.3 on 2024-06-05 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0006_alter_trade_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="counteroffer_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="trades.proposal",
                verbose_name="Propuesta previa",
            ),
        ),
    ]
