# Generated by Django 5.0.3 on 2024-07-02 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0008_valoration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valoration",
            name="trade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="trades.trade",
                verbose_name="trade",
            ),
        ),
    ]
