# Generated by Django 5.0.3 on 2024-07-02 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0009_alter_valoration_trade"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Valoration",
        ),
    ]
